esphome:
  name: fensteruberwachung-1

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fensteruberwachung-1"
    password: !secret wifi_password

web_server:
  port: 80

captive_portal:
    
binary_sensor:
# Kanal 1
  - platform: gpio
    pin: 35
    name: "Kanal 1"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 2
  - platform: gpio
    pin: 32
    name: "Kanal 2"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 3
  - platform: gpio
    pin: 33
    name: "Kanal 3"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 4
  - platform: gpio
    pin: 25
    name: "Kanal 4"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 5
  - platform: gpio
    pin: 26
    name: "Kanal 5"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 6
  - platform: gpio
    pin: 27
    name: "Kanal 6"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 7
  - platform: gpio
    pin: 14
    name: "Kanal 7"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
# Kanal 8
  - platform: gpio
    pin: 12
    name: "Kanal 8"
    device_class: window
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms